/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brainfuck;


/**
 *
 * @author johannes
 */
public class ConsoleFrame extends javax.swing.JFrame {
    
    private static String code;
    private static String codeSaved;
    private static boolean twoBytes;
    private boolean twoBytesSaved;
    private Interpreter interpreter;
    private boolean needInput = false;
    /**
     * Creates new form Console
     */
    public ConsoleFrame() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        textFieldIn.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOut = new javax.swing.JTextArea();
        textFieldIn = new javax.swing.JTextField();
        buttonRerun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brainfuck Console");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        textAreaOut.setColumns(20);
        textAreaOut.setRows(5);
        textAreaOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAreaOutKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaOut);

        textFieldIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldInKeyTyped(evt);
            }
        });

        buttonRerun.setText("Run again");
        buttonRerun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRerunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textFieldIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRerun))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRerun)
                    .addComponent(textFieldIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        codeSaved = ConsoleFrame.code;
        twoBytesSaved = twoBytes;
        
        run();
    }//GEN-LAST:event_formWindowOpened

    private void buttonRerunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRerunActionPerformed
        interpreter.interrupt();
        
        while(interpreter.isAlive()) {
            
        }
        textFieldIn.grabFocus();
        run();
    }//GEN-LAST:event_buttonRerunActionPerformed

    private void textFieldInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldInKeyTyped
        evt.consume();
        if(needInput) {
                needInput = false;
                
                textFieldIn.setText(textFieldIn.getText() + evt.getKeyChar());
                
                sendInput(evt.getKeyChar());
        }
    }//GEN-LAST:event_textFieldInKeyTyped

    private void textAreaOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaOutKeyTyped
        evt.consume();
    }//GEN-LAST:event_textAreaOutKeyTyped
            
    private void run() {
        clearText();
        interpreter = new Interpreter(codeSaved, twoBytesSaved, this);
        interpreter.start();
    }
    
    private void clearText() {
        textAreaOut.setText("");
        textFieldIn.setText("");
    }
    
    public void addText(char chr) {
        textAreaOut.setText(textAreaOut.getText() + String.valueOf(chr));
    }
    
    public void requestInput() {
        needInput = true;
    }
    
    public void sendInput(char chr) {
        interpreter.setInput(chr);
    }
    
    /**
     * 
     * @param code
     * @param twoBytes
     */
    public static void main(String code, boolean twoBytes) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsoleFrame().setVisible(true);
            }
        });
        
        ConsoleFrame.code = code;
        ConsoleFrame.twoBytes = twoBytes;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRerun;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaOut;
    private javax.swing.JTextField textFieldIn;
    // End of variables declaration//GEN-END:variables
}
